### ISSUE TITLE
CodeCopy plugin doesn't work on Firefox in new portal workshop platform

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/workshops#14]
The CodeCopy plugin doesn't work on Firefox in new portal workshop platform.
The default browser was Chromium on old platform.  But it looks like CodeCopy is supported on Firefox too.
https://addons.mozilla.org/en-US/firefox/addon/codecopy/

**Comment by bcollard** [comment]
restart Firefox if needed. Also, you can go to Firefox extension and verify the extension is enabled (and then restart the browser again)

**Comment by jameshbarton** [comment]
This is no longer an issue.
